ht_platform_home:
    path:     /{page}
    defaults:
        _controller: HTPlatformBundle:Advert:index
        page:        1
    requirements:
        page: \d*

ht_platform_view:
    path:     /advert/{id}
    defaults: 
        _controller: HTPlatformBundle:Advert:view
    requirements:
        id: \d*

ht_platform_add:
    path:     /add
    defaults:
        _controller: HTPlatformBundle:Advert:add 

ht_platform_edit:
    path:     /edit/{id}
    defaults:  
        _controller: HTPlatformBundle:Advert:edit
    requirements:
        id: \d*

ht_platform_delete:
    path:     /delete/{id}
    defaults:
        _controller:  HTPlatformBundle:Advert:delete
    requirements:
        id: \d*

ht_platform_view_slug:
    path:     /{year}/{slug}.{_format}
    defaults: 
        _controller: HTPlatformBundle:Advert:viewSlug
        _format:      html
    requirements:
        year:   \d{4}
        _format:  html|xml
